# Generated by Django 6.0.4 on 2026-05-05 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_created_user_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
